<?php

namespace frontend\modules\cabinet;

use yii\filters\AccessControl;

/**
 * cabinet module definition class
 */
class Module extends \yii\base\Module
{
    /**
     * {@inheritdoc}
     */
    public $controllerNamespace = 'frontend\Modules\Cabinet\Controllers';

    public function getViewPath()
    {
        return \Yii::getAlias('@frontend/Modules/Cabinet/Views');
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }
}
